version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/packages/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/packages/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/packages/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
